name: ChestKitPro
version: 1.0.0
authors:
  - WavyCraft
  - Terpz710
api: 5.0.0
main: wavycraft\chestkit\Loader

softdepend: ["PiggyCustomEnchants"]

permissions:
  chestkitpro.cmd:
    default: true
